export const mockData = [
  {
    id: 1,
    name: "Manohar Batra",
    designation: "Sr Frontend Developer",
    domain: "SDE",
    expertise: "Frontend",
    yoe: "10",
    skills: ["React.js", "System Design"],
    companies: ["IBM", "QAD", "TCS"],
    industry: ["Service"],
    linkedinLink: "https://www.linkedin.com/in/manoharbatra/",
    topmateLink: "https://www.topmate.io/manohar",
    active: true,
  },
  {
    id: 2,
    name: "Manish Goyal",
    designation: "SDE-2",
    domain: "SDE",
    expertise: "Backend",
    yoe: "3.5",
    skills: [
      "Java",
      "Spring Boot",
      "System Design",
      "Kafka",
      "Microservices",
      "DSA",
    ],
    companies: ["LinkedIn", "Flipkart"],
    industry: ["Product"],
    linkedinLink: "https://www.linkedin.com/in/manish-goyal-8900b2188/",
    topmateLink: "https://topmate.io/manish_goyal17/",
    active: true,
  },
  {
    id: 3,
    name: "Samarh Wath",
    designation: "Associate Consultant",
    domain: "SDE",
    expertise: "Backend",
    yoe: "4.5",
    skills: ["Java", "Spring Boot", "Kafka", "Microservices"],
    companies: ["Infosys", "Systango"],
    industry: ["Service"],
    linkedinLink: "https://www.linkedin.com/in/samarth-wath-24588b159/",
    topmateLink: "https://topmate.io/samarth_wath",
    active: true,
  },
  {
    id: 4,
    name: "Nitik Narang",
    designation: "Backend Developer",
    domain: "SDE",
    expertise: "Full Stack",
    yoe: "3",
    skills: ["React.js", "System Design", "Nodejs", "ExpressJs", "AWS", "DSA"],
    companies: ["IBM", "TCS"],
    industry: ["Service"],
    linkedinLink: "https://www.linkedin.com/in/nitik-narang-a77116170",
    topmateLink: "https://topmate.io/nitik_narang/",
    active: true,
  },
  {
    id: 5,
    name: "Manali Borkar",
    designation: "Deputy manager",
    domain: "ERP",
    expertise: "SAP",
    yoe: "7",
    skills: ["SAP ABAP", "SAP HANA"],
    companies: ["Deloitte", "PwC", "Capgemini"],
    industry: ["Big4", "Service"],
    linkedinLink: "https://www.linkedin.com/in/manali-borkar-781a3513b/",
    topmateLink: "https://topmate.io/manali_borkar",
    active: true,
  },
  {
    id: 6,
    name: "Om Sharma",
    designation: "Associate Consultant",
    domain: "SDE",
    expertise: "Backend",
    yoe: "4.8",
    skills: [".Net", "Azure Cloud", "React.js", "System Design"],
    companies: ["Cognizant", "Publicis Sapient"],
    industry: ["Service"],
    linkedinLink: "https://www.linkedin.com/in/developeromsharma/",
    topmateLink: "https://www.topmate.io/developeromsharma",
    active: true,
  },
];
